# Generated by Django 2.0.6 on 2018-07-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180617_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bike',
            field=models.CharField(default='Your favorite bike...', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(default='Country you live in...', max_length=50),
        ),
    ]
