# Generated by Django 2.0.7 on 2018-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180718_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(default='Câteva cuvinte depsre tine...', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bike',
            field=models.CharField(default='Bicicleta favorită...', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(default='România', max_length=50),
        ),
    ]
