# Generated by Django 2.0.6 on 2018-06-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trails.Trail'),
        ),
    ]
