# Generated by Django 2.0.6 on 2018-06-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_auto_20180613_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='image',
            field=models.ImageField(default='imagelink', upload_to='image/'),
        ),
    ]
