# Generated by Django 2.0.6 on 2018-06-20 14:19

from django.db import migrations, models
import trails.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_trail_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='distance',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='trail',
            name='region',
            field=models.CharField(default='Romania', max_length=100),
        ),
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=5),
        ),
        migrations.AlterField(
            model_name='trail',
            name='image',
            field=models.ImageField(default='imagelink.jpg', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='track',
            field=models.FileField(default='tracklink.kml', upload_to='tracks/', validators=[trails.validators.validate_file_extension]),
        ),
    ]
