# Generated by Django 2.0.6 on 2018-06-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_auto_20180620_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='homepage_staff_pick',
            field=models.BooleanField(default=0),
        ),
    ]
