# Generated by Django 2.0.6 on 2018-06-13 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_auto_20180607_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='image',
            field=models.ImageField(default='imagelink', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='trail',
            name='image_uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
