# Generated by Django 2.0.6 on 2018-06-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180606_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(default='A couple of words about yourself...', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bike',
            field=models.CharField(default='Merida Mats', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
