# Generated by Django 2.0.6 on 2018-06-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_auto_20180613_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
