# Generated by Django 2.0.6 on 2018-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0009_trail_homepage_staff_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=10),
        ),
    ]
