# Generated by Django 2.0.6 on 2018-07-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0011_auto_20180718_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=50, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='region',
            field=models.CharField(choices=[('Banat', 'Banat'), ('Bucovina', 'Bucovina'), ('Crișana', 'Crișana'), ('Dobrogea', 'Dobrogea'), ('Maramureș', 'Maramureș'), ('Moldova', 'Moldova'), ('Muntenia', 'Muntenia'), ('Oltenia', 'Oltenia'), ('Transilvania', 'Transilvania')], max_length=100),
        ),
    ]
